apiVersion: apps/v1
kind: Deployment
metadata:
  name: doings-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doings-app
  template:
    metadata:
      labels:
        app: doings-app
    spec:
      containers:
        - name: doings-container
          image: doingsacr.azurecr.io/doings/nodejs-webapp  # Corrected image URL
          ports:
            - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: doings-service
spec:
  selector:
    app: doings-app
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: LoadBalancer
